### ISSUE TITLE
Lizard 11.1.5

### ISSUE THREAD

**Issue by CPagador** [liamt19/Lizard#110]
Hi,

Jim Ablett compiled this version and posted it here:

https://talkchess.com/viewtopic.php?p=973326#p973326

I did some tests and definetely something is wrong with this version.

In my blitz tournament:

https://talkchess.com/viewtopic.php?t=84594&start=20

Lizard 11.1 got 32.5/60

I ran a gauntlet for Lizard 11.1.5 JA against the same opponents and it only got 4/60:

https://www.mediafire.com/file/y800ty45vtfxu80/Div1_Ed50gt.pgn/file

Regards,
Carlos

**Comment by liamt19** [comment]
Hi Carlos, that compile was built using the incorrect weights file which resulted in that poor performance. I've just done a round of compilations myself which you can get here: 

https://github.com/liamt19/Lizard/releases/tag/v11.1.5
